### ISSUE TITLE
V.6 Implement Sequence tab on View page

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-learns-git#11]
## User Story
As a user, I want to be able to view a list of all the terms and definitions in each sequence that is in a study set, so I know what I will be studying. I should be able to select different sequences I want to view. 

## Sub-tasks
- [ ] Create card component (for list)
- [ ] Create side panel for selecting sequences in the "contents" container under tabs
- [ ] Show list of cards in the selected sequence next to side panel
